# Generated by Django 5.1.4 on 2026-04-16 19:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0013_convert_lesson_and_course_durations_to_durationfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('multiple', 'Opción múltiple'), ('verdadero_falso', 'Verdadero o Falso')], default='multiple', max_length=20, verbose_name='Tipo')),
                ('texto', models.TextField(verbose_name='Texto de la pregunta')),
                ('puntaje', models.PositiveSmallIntegerField(default=1, verbose_name='Puntaje')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['simulador', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=500, verbose_name='Texto de la opción')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='Es correcta')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='simuladores.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
                'ordering': ['pregunta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ExplicacionPregunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto de explicación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='simuladores/explicaciones/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pregunta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explicacion', to='simuladores.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Explicación de pregunta',
                'verbose_name_plural': 'Explicaciones de preguntas',
            },
        ),
        migrations.CreateModel(
            name='Simulador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='simuladores/portadas/', verbose_name='Imagen portada')),
                ('imagen_portada_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Imagen portada URL')),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('tiempo_limite_minutos', models.PositiveIntegerField(default=60, verbose_name='Tiempo límite (minutos)')),
                ('max_intentos', models.PositiveIntegerField(default=1, verbose_name='Intentos permitidos')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simuladores', to='cursos.curso', verbose_name='Curso')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simuladores', to='cursos.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Simulador',
                'verbose_name_plural': 'Simuladores',
                'ordering': ['titulo'],
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='simulador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='simuladores.simulador', verbose_name='Simulador'),
        ),
        migrations.CreateModel(
            name='IntentoSimulador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado en')),
                ('finalizado_en', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado en')),
                ('tiempo_transcurrido_segundos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo transcurrido (segundos)')),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Puntaje obtenido')),
                ('total_correctas', models.PositiveSmallIntegerField(default=0, verbose_name='Correctas')),
                ('total_incorrectas', models.PositiveSmallIntegerField(default=0, verbose_name='Incorrectas')),
                ('total_no_respondidas', models.PositiveSmallIntegerField(default=0, verbose_name='No respondidas')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_simulador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('simulador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='simuladores.simulador', verbose_name='Simulador')),
            ],
            options={
                'verbose_name': 'Intento de simulador',
                'verbose_name_plural': 'Intentos de simulador',
                'ordering': ['-iniciado_en'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaIntento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_correcta', models.BooleanField(default=False, verbose_name='Es correcta')),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='simuladores.intentosimulador', verbose_name='Intento')),
                ('opcion_elegida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='simuladores.opcion', verbose_name='Opción elegida')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='simuladores.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de intento',
                'verbose_name_plural': 'Respuestas de intento',
                'unique_together': {('intento', 'pregunta')},
            },
        ),
    ]
