# Generated by Django 5.1.4 on 2026-04-16 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simuladores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimuladorDisponibilidadUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField(verbose_name='Fecha de apertura')),
                ('fecha_cierre', models.DateTimeField(verbose_name='Fecha de cierre')),
                ('motivo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disponibilidades_simulador_creadas', to=settings.AUTH_USER_MODEL)),
                ('simulador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_usuario', to='simuladores.simulador', verbose_name='Simulador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_simulador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Disponibilidad de simulador por usuario',
                'verbose_name_plural': 'Disponibilidades de simulador por usuario',
                'unique_together': {('simulador', 'user')},
            },
        ),
    ]
