# Generated by Django

from django.db import migrations


def create_default_categories(apps, schema_editor):
    """Create default ticket categories"""
    
    # We'll create categories directly in the database
    TicketCategory = apps.get_model('tickets', 'TicketCategory')
    
    default_categories = [
        {
            'name': 'Soporte Técnico',
            'description': 'Problemas técnicos con la plataforma, acceso, funcionalidades',
            'icon': 'HelpCircle',
            'color': '#3B82F6',
            'order': 1,
            'is_active': True
        },
        {
            'name': 'Soporte Académico',
            'description': 'Consultas sobre cursos, matrículas, calificaciones',
            'icon': 'BookOpen',
            'color': '#10B981',
            'order': 2,
            'is_active': True
        },
        {
            'name': 'Problemas de Cuenta',
            'description': 'Dificultades con inicio de sesión, perfil, configuración',
            'icon': 'User',
            'color': '#F59E0B',
            'order': 3,
            'is_active': True
        },
        {
            'name': 'Sugerencias',
            'description': 'Ideas y sugerencias para mejorar la plataforma',
            'icon': 'Lightbulb',
            'color': '#8B5CF6',
            'order': 4,
            'is_active': True
        },
        {
            'name': 'Reporte de Errores',
            'description': 'Reportar bugs o errores encontrados en el sistema',
            'icon': 'AlertTriangle',
            'color': '#EF4444',
            'order': 5,
            'is_active': True
        }
    ]
    
    for category_data in default_categories:
        TicketCategory.objects.create(**category_data)


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_default_categories,
            reverse_code=migrations.RunPython.noop
        ),
    ]
