# Generated by Django 6.0.3 on 2026-03-31 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='tickets_not_recipie_a596ee_idx',
            old_name='tickets_noti_recipie_2e0f04_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='tickets_not_created_7aaffb_idx',
            old_name='tickets_noti_created_88e841_idx',
        ),
    ]
