# Generated by Django 6.0.3 on 2026-03-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='maternal_surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='paternal_surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
