export const PERMISSIONS_CATALOG = {
  pages: {
    label: 'Acceso a Paginas',
    help: 'Controla que pantallas puede abrir el rol.',
    actions: [
      { key: 'dashboard', label: 'Inicio' },
      { key: 'calendario', label: 'Calendario' },
      { key: 'cursos', label: 'Cursos' },
      { key: 'simuladores', label: 'Simuladores' },
      { key: 'recursos', label: 'Recursos' },
      { key: 'flashcards', label: 'Flashcards' },
      { key: 'tickets', label: 'Tickets' },
      { key: 'matriculas', label: 'Matriculas' },
      { key: 'rutas', label: 'Rutas' },
      { key: 'categorias', label: 'Categorias' },
      { key: 'users', label: 'Usuarios' },
      { key: 'roles', label: 'Roles' },
      { key: 'configuracion', label: 'Configuracion' },
    ],
  },
  users: {
    label: 'Usuarios',
    actions: [
      { key: 'read', label: 'Ver' },
      { key: 'create', label: 'Crear' },
      { key: 'update', label: 'Editar' },
      { key: 'delete', label: 'Eliminar' },
      { key: 'assign_role', label: 'Asignar Rol' },
      { key: 'update_profile', label: 'Editar Perfil' },
    ],
  },
  roles: {
    label: 'Roles',
    actions: [
      { key: 'read', label: 'Ver' },
      { key: 'create', label: 'Crear' },
      { key: 'update', label: 'Editar' },
      { key: 'delete', label: 'Eliminar' },
      { key: 'assign_permissions', label: 'Editar Permisos' },
    ],
  },
  courses: {
    label: 'Cursos',
    actions: [
      { key: 'read', label: 'Ver Listado' },
      { key: 'create', label: 'Crear' },
      { key: 'update', label: 'Editar' },
      { key: 'delete', label: 'Eliminar' },
      { key: 'view_content', label: 'Ver Contenido' },
      { key: 'view_mediateca', label: 'Ver Mediateca' },
      { key: 'view_price', label: 'Ver Precio' },
      { key: 'manage_enrollments', label: 'Gestionar Matriculas' },
    ],
  },
  simulators: {
    label: 'Simuladores',
    actions: [
      { key: 'read', label: 'Ver Listado' },
      { key: 'create', label: 'Crear' },
      { key: 'update', label: 'Editar' },
      { key: 'delete', label: 'Eliminar' },
      { key: 'resolve', label: 'Resolver' },
      { key: 'view_attempts', label: 'Ver Intentos' },
      { key: 'view_ranking', label: 'Ver Ranking' },
      { key: 'manage_questions', label: 'Gestionar Preguntas' },
      { key: 'manage_availability', label: 'Gestionar Disponibilidad' },
    ],
  },
  resources: {
    label: 'Recursos',
    actions: [
      { key: 'read', label: 'Ver' },
      { key: 'create', label: 'Crear' },
      { key: 'update', label: 'Editar' },
      { key: 'delete', label: 'Eliminar' },
      { key: 'read_enrolled', label: 'Ver Solo Matriculados' },
    ],
  },
  flashcards: {
    label: 'Flashcards',
    actions: [
      { key: 'read', label: 'Ver' },
      { key: 'create', label: 'Crear' },
      { key: 'update', label: 'Editar Cualquiera' },
      { key: 'delete', label: 'Eliminar Cualquiera' },
      { key: 'update_own', label: 'Editar Propias' },
      { key: 'delete_own', label: 'Eliminar Propias' },
      { key: 'study', label: 'Estudiar' },
    ],
  },
  tickets: {
    label: 'Tickets',
    actions: [
      { key: 'read', label: 'Ver Todos' },
      { key: 'create', label: 'Crear' },
      { key: 'update', label: 'Editar Cualquiera' },
      { key: 'delete', label: 'Eliminar Cualquiera' },
      { key: 'read_own', label: 'Ver Propios' },
      { key: 'update_own', label: 'Editar Propios' },
      { key: 'respond', label: 'Responder' },
    ],
  },
  categories: {
    label: 'Categorias',
    actions: [
      { key: 'read', label: 'Ver' },
      { key: 'create', label: 'Crear' },
      { key: 'update', label: 'Editar' },
      { key: 'delete', label: 'Eliminar' },
    ],
  },
  enrollments: {
    label: 'Matriculas',
    actions: [
      { key: 'read', label: 'Ver Todas' },
      { key: 'create', label: 'Crear' },
      { key: 'update', label: 'Editar' },
      { key: 'delete', label: 'Eliminar' },
      { key: 'read_own', label: 'Ver Propias' },
    ],
  },
  routes: {
    label: 'Rutas',
    actions: [
      { key: 'read', label: 'Ver' },
      { key: 'create', label: 'Crear' },
      { key: 'update', label: 'Editar' },
      { key: 'delete', label: 'Eliminar' },
    ],
  },
  reports: {
    label: 'Reportes',
    actions: [
      { key: 'read', label: 'Ver' },
      { key: 'create', label: 'Crear' },
      { key: 'update', label: 'Editar' },
      { key: 'delete', label: 'Eliminar' },
      { key: 'export', label: 'Exportar' },
    ],
  },
}

export const RESOURCE_ORDER = [
  'pages',
  'users',
  'roles',
  'courses',
  'simulators',
  'resources',
  'flashcards',
  'tickets',
  'categories',
  'enrollments',
  'routes',
  'reports',
]
