# Generated by Django 6.0.3 on 2026-04-01 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250, unique=True, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('orden', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('imagen_portada_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Imagen portada URL')),
                ('nivel', models.CharField(choices=[('basico', 'Basico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='avanzado', max_length=15, verbose_name='Nivel')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('proximo', 'Proximo'), ('bloqueado', 'Bloqueado')], default='disponible', max_length=15, verbose_name='Estado')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('orden', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True, verbose_name='Slug')),
                ('video_intro_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Video intro URL')),
                ('tiene_mediateca', models.BooleanField(default=False, verbose_name='Tiene mediateca')),
                ('total_lecciones', models.SmallIntegerField(default=0, verbose_name='Total lecciones')),
                ('duracion_total_min', models.IntegerField(default=0, verbose_name='Duracion total en minutos')),
                ('fecha_disponible_desde', models.DateField(blank=True, null=True, verbose_name='Fecha disponible desde')),
                ('fecha_disponible_hasta', models.DateField(blank=True, null=True, verbose_name='Fecha disponible hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['ruta', 'orden', 'titulo'],
                'indexes': [models.Index(fields=['ruta'], name='cursos_curs_ruta_id_0604a1_idx'), models.Index(fields=['ruta', 'publicado'], name='cursos_curs_ruta_id_f4c47d_idx'), models.Index(fields=['ruta', 'orden'], name='cursos_curs_ruta_id_8b0738_idx'), models.Index(fields=['estado'], name='cursos_curs_estado_d21fd6_idx'), models.Index(fields=['fecha_disponible_desde'], name='cursos_curs_fecha_d_3f587b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_disponible_hasta__isnull', True), ('fecha_disponible_desde__isnull', True), ('fecha_disponible_hasta__gte', models.F('fecha_disponible_desde')), _connector='OR'), name='curso_fechas_disponibles_validas')],
            },
        ),
    ]
