# Generated by Django 6.0.3 on 2026-04-01 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaCurso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_acceso', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='cursos.curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_curso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matricula de curso',
                'verbose_name_plural': 'Matriculas de curso',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='cursos_matr_user_id_ddde78_idx'), models.Index(fields=['curso'], name='cursos_matr_curso_i_f44e00_idx'), models.Index(fields=['activa'], name='cursos_matr_activa_18ed37_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'curso'), name='unique_matricula_curso_user_curso'), models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_inicio__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='matricula_curso_fechas_validas')],
            },
        ),
        migrations.CreateModel(
            name='MatriculaRuta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_acceso', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='cursos.ruta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_ruta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matricula de ruta',
                'verbose_name_plural': 'Matriculas de ruta',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='cursos_matr_user_id_ce7d93_idx'), models.Index(fields=['ruta'], name='cursos_matr_ruta_id_12ca68_idx'), models.Index(fields=['activa'], name='cursos_matr_activa_b58217_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'ruta'), name='unique_matricula_ruta_user_ruta'), models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_inicio__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='matricula_ruta_fechas_validas')],
            },
        ),
    ]
