# Generated by Django 6.0.3 on 2026-04-01 18:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_matriculacurso_matricularuta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Seccion',
                'verbose_name_plural': 'Secciones',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('video_url', models.CharField(max_length=500)),
                ('duracion_min', models.PositiveIntegerField(default=0)),
                ('orden', models.SmallIntegerField(default=0)),
                ('publicado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='cursos.seccion')),
            ],
            options={
                'verbose_name': 'Leccion',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioCurso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='cursos.curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_curso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de curso',
                'verbose_name_plural': 'Comentarios de curso',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['curso', 'created_at'], name='cursos_come_curso_i_2caceb_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediatecaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('documento', 'Documento'), ('enlace', 'Enlace')], default='documento', max_length=20)),
                ('url', models.CharField(max_length=500)),
                ('orden', models.SmallIntegerField(default=0)),
                ('publicado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediateca_items', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Item de mediateca',
                'verbose_name_plural': 'Items de mediateca',
                'ordering': ['orden', 'titulo'],
                'indexes': [models.Index(fields=['curso', 'orden'], name='cursos_medi_curso_i_543059_idx'), models.Index(fields=['publicado'], name='cursos_medi_publica_fc6792_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgresoLeccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('porcentaje', models.PositiveSmallIntegerField(default=0)),
                ('completada', models.BooleanField(default=False)),
                ('ultimo_acceso', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='cursos.leccion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_leccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de leccion',
                'verbose_name_plural': 'Progresos de leccion',
                'ordering': ['-ultimo_acceso'],
                'indexes': [models.Index(fields=['user'], name='cursos_prog_user_id_f10bb6_idx'), models.Index(fields=['leccion'], name='cursos_prog_leccion_670d2a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'leccion'), name='unique_progreso_user_leccion'), models.CheckConstraint(condition=models.Q(('porcentaje__gte', 0), ('porcentaje__lte', 100)), name='progreso_leccion_porcentaje_valido')],
            },
        ),
        migrations.AddIndex(
            model_name='seccion',
            index=models.Index(fields=['curso', 'orden'], name='cursos_secc_curso_i_6c27a9_idx'),
        ),
        migrations.AddIndex(
            model_name='leccion',
            index=models.Index(fields=['seccion', 'orden'], name='cursos_lecc_seccion_a10f77_idx'),
        ),
        migrations.AddIndex(
            model_name='leccion',
            index=models.Index(fields=['publicado'], name='cursos_lecc_publica_406a5b_idx'),
        ),
    ]
