# Generated by Django 6.0.3 on 2026-04-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_curso_imagen_portada'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='curso',
            name='curso_fechas_disponibles_validas',
        ),
        migrations.RemoveIndex(
            model_name='curso',
            name='cursos_curs_fecha_d_3f587b_idx',
        ),
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio'),
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha_disponible_desde',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha_disponible_hasta',
        ),
    ]
