# Generated by Django 5.2.5 on 2026-04-14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_remove_curso_curso_fechas_disponibles_validas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculacurso',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='matriculacurso',
            name='numero_cuotas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='matriculacurso',
            name='plan_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Credito')], default='contado', max_length=10),
        ),
        migrations.AddField(
            model_name='matricularuta',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='matricularuta',
            name='numero_cuotas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='matricularuta',
            name='plan_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Credito')], default='contado', max_length=10),
        ),
        migrations.CreateModel(
            name='CuotaPagoMatricula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveSmallIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matricula_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_pago', to='cursos.matriculacurso')),
                ('matricula_ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_pago', to='cursos.matricularuta')),
            ],
            options={
                'verbose_name': 'Cuota de pago',
                'verbose_name_plural': 'Cuotas de pago',
                'ordering': ['numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='cuotapagomatricula',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('matricula_ruta__isnull', False), ('matricula_curso__isnull', True)), models.Q(('matricula_ruta__isnull', True), ('matricula_curso__isnull', False)), _connector='OR'), name='cuota_pago_unica_matricula_origen'),
        ),
        migrations.AddConstraint(
            model_name='cuotapagomatricula',
            constraint=models.UniqueConstraint(fields=('matricula_ruta', 'numero'), name='unique_cuota_numero_matricula_ruta'),
        ),
        migrations.AddConstraint(
            model_name='cuotapagomatricula',
            constraint=models.UniqueConstraint(fields=('matricula_curso', 'numero'), name='unique_cuota_numero_matricula_curso'),
        ),
        migrations.AddIndex(
            model_name='cuotapagomatricula',
            index=models.Index(fields=['matricula_ruta'], name='cursos_cuot_matricu_b60ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='cuotapagomatricula',
            index=models.Index(fields=['matricula_curso'], name='cursos_cuot_matricu_a840de_idx'),
        ),
        migrations.AddIndex(
            model_name='cuotapagomatricula',
            index=models.Index(fields=['fecha_pago'], name='cursos_cuot_fecha_p_ca837d_idx'),
        ),
        migrations.AddIndex(
            model_name='cuotapagomatricula',
            index=models.Index(fields=['estado'], name='cursos_cuot_estado_16413b_idx'),
        ),
    ]
