# Generated by Django 5.2.5 on 2026-04-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_matricula_planes_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculacurso',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_curso_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matricularuta',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_ruta_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
