# Generated by Django 5.2.5 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_matricula_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotapagomatricula',
            name='fecha_pago_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuotapagomatricula',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cuotapagomatricula',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=12),
        ),
    ]
