# Generated by Django 5.1.4 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_comprobantepago'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantepago',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_cuota/'),
        ),
    ]
