# Generated by Django 5.1.4 on 2026-04-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_comprobantepago_comprobante_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantepago',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
